from __future__ import annotations

from .classification import (
    build_stacking_classifier,
    build_fast_multilabel_classifier,
    build_supervised_pipeline,
    count_multilabel_tags,
    filter_rare_multilabel_tags,
)
from .clustering import (
    reduce_features_dimensionality,
    fit_minibatch_kmeans_range_fast,
    fit_gmm,
    fit_lda_topics,
    extract_top_words,
    topic_terms_map,
    cosine_similarity_matrix,
    recommend_by_cosine,
    get_top_neighbors_by_cosine,
    recommendation_pearson_fast,
)
from .evaluation import compute_multilabel_metrics, cluster_metrics_from_silhouette
from .preprocessing import (
    clean,
    remove_stopwords,
    lematize,
    preprocess,
    parse_tags,
    preprocess_tags,
    normalize_poetry_columns
)
from .features import build_feature_pipeline, row_l2_norms
from .integration import (
    parse_json_list,
    json_dumps_list,
    build_integrated_results,
    cluster_tag_crosstab,
    cluster_topic_crosstab,
    cluster_poet_crosstab,
    cluster_source_crosstab,
    poet_tag_crosstab,
    top_tags_by_cluster,
    build_vallejo_view,
)
from .io import (
    PROJECT_ROOT,
    ARTIFACTS_DIR,
    DATA_DIR,
    FIGS_DIR,
    artifact_path,
    data_path,
    fig_path,
    ensure_dir,
    save_joblib,
    load_joblib,
    save_csv,
    load_csv,
    save_json,
    load_json,
)

__all__ = [
    'build_stacking_classifier',
    'build_fast_multilabel_classifier',
    'build_supervised_pipeline',
    'count_multilabel_tags',
    'filter_rare_multilabel_tags',
    'reduce_features_dimensionality',
    'fit_minibatch_kmeans_range_fast',
    'fit_gmm',
    'fit_lda_topics',
    'extract_top_words',
    'topic_terms_map',
    'cosine_similarity_matrix',
    'recommend_by_cosine',
    'get_top_neighbors_by_cosine',
    'recommendation_pearson_fast',
    'compute_multilabel_metrics',
    'cluster_metrics_from_silhouette',
    'clean',
    'remove_stopwords',
    'lematize',
    'preprocess',
    'parse_tags',
    'preprocess_tags',
    'normalize_poetry_columns',
    'build_feature_pipeline',
    'row_l2_norms',
    'parse_json_list',
    'json_dumps_list',
    'build_integrated_results',
    'cluster_tag_crosstab',
    'cluster_topic_crosstab',
    'cluster_poet_crosstab',
    'cluster_source_crosstab',
    'poet_tag_crosstab',
    'top_tags_by_cluster',
    'build_vallejo_view',
    'PROJECT_ROOT',
    'ARTIFACTS_DIR',
    'DATA_DIR',
    'FIGS_DIR',
    'artifact_path',
    'data_path',
    'fig_path',
    'ensure_dir',
    'save_joblib',
    'load_joblib',
    'save_csv',
    'load_csv',
    'save_json',
    'load_json',
]
